project_id = "wcqjmjceelcainyyqjmi"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.sync-stripe-price]
    verify_jwt = false
  [functions.ai-schedule]
    verify_jwt = false
  [functions.ai-suggest-tasks]
    verify_jwt = false
  [functions.session-notes-webhook]
    verify_jwt = false
  [functions.send-telegram-notification]
    verify_jwt = false
